config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  get '/articles/:id' => 'spree/static_content#article'
  get '/admin/articles' => 'spree/admin/pages#articles_index'
  get '/admin/add_article' => 'spree/admin/pages#add_article'
  get '/admin/edit_article/:article_item_id' => 'spree/admin/pages#edit_article'
  get '/admin/delete_article/:article_item_id' => 'spree/admin/pages#delete_article'
  post '/articles' => 'articles#create_article'
  patch '/articles' => 'spree/admin/pages#update_article'

  get '/admin/baloons' => 'spree/admin/pages#baloons_index'
  get '/admin/add_baloon' => 'spree/admin/pages#add_baloon'
  get '/admin/edit_baloon/:baloon_item_id' => 'spree/admin/pages#edit_baloon'
  get '/admin/delete_baloon/:baloon_item_id' => 'spree/admin/pages#delete_baloon'
  post '/baloons' => 'spree/admin/pages#create_baloon'
  patch '/baloons' => 'spree/admin/pages#update_baloon'

  get '/admin/materials' => 'spree/admin/pages#materials_index'
  get '/admin/add_material' => 'spree/admin/pages#add_material'
  get '/admin/edit_material/:material_item_id' => 'spree/admin/pages#edit_material'
  get '/admin/delete_material/:material_item_id' => 'spree/admin/pages#delete_material'
  post '/materials' => 'spree/admin/pages#create_material'
  patch '/materials' => 'spree/admin/pages#update_material'

  get 'export_xml' => 'spree/products#xml_export', :defaults => { :format => 'xml' }

end

app/controllers/spree/admin/pages_controller.rb
class Spree::Admin::PagesController < Spree::Admin::ResourceController


  def articles_index
    @articles = Article.all
  end

  def edit_article
    @article = Article.find(params[:article_item_id])
  end

  def add_article
    @article = Article.new
  end
  def baloons_index
    @baloons = Baloon.all
  end

  def edit_baloon
    @baloon = Baloon.find(params[:baloon_item_id])
  end

  def add_baloon
    @baloon = Baloon.new
  end

  def create_article
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to '/admin/articles', notice: 'Статья создана' }
      else
        format.html { redirect_to :back, notice: 'Ошибка!' }
      end
    end
  end

  def update_article
    @article = Article.find(params[:article][:id])
    respond_to do |format|
      if  @article.update(article_params)
        format.html { redirect_to '/admin/articles', notice: 'Статья отредактирована' }
      else
        format.html { redirect_to :back, notice: 'Ошибка!' }
      end
    end
  end
  def create_baloon
    @article = Baloon.new(baloon_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to '/admin/baloons', notice: 'Метка создана' }
      else
        format.html { redirect_to :back, notice: 'Ошибка!' }
      end
    end
  end

  def update_baloon
    @article = Baloon.find(params[:baloon][:id])
    respond_to do |format|
      if  @article.update(baloon_params)
        format.html { redirect_to '/admin/baloons', notice: 'Метка отредактирована' }
      else
        format.html { redirect_to :back, notice: 'Ошибка!' }
      end
    end
  end

  def delete_article
    Article.find(params[:article_item_id]).destroy
    redirect_to :back
  end






  def materials_index
    @materials = Material.all

  end

  def edit_material
    @material = Material.find(params[:material_item_id])
  end

  def add_material
    @material = Material.new
  end

  def create_material
    @material = Material.new(material_params)
    unless params[:material][:file].blank?
    require 'fileutils'
    tmp = params[:material][:file].tempfile
    file = File.join("public/materials", params[:material][:file].original_filename)
    FileUtils.cp tmp.path, file
    @material.file = '/materials/'+file.split('/').last
    end
    respond_to do |format|
      if @material.save
        format.html { redirect_to '/admin/materials', notice: 'Материал добавлен' }
      else
        format.html { redirect_to :back, notice: 'Ошибка!' }
      end
    end
  end

  def update_material
    @material = Material.find(params[:material][:id])
    unless params[:material][:file].blank?
    require 'fileutils'
    tmp = params[:material][:file].tempfile
    file = File.join("public/materials", params[:material][:file].original_filename)
    FileUtils.cp tmp.path, file
    @material.file = '/materials/'+file.split('/').last
    end

    respond_to do |format|
      if  @material.update(material_params)
        format.html { redirect_to '/admin/materials', notice: 'Материал отредактирован' }
      else
        format.html { redirect_to :back, notice: 'Ошибка!' }
      end
    end
  end

  def delete_material
    Material.find(params[:material_item_id]).destroy
    redirect_to :back
  end
  def delete_baloon
    Material.find(params[:baloon_item_id]).destroy
    redirect_to :back
  end




  private

  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :text, :teaser, :slug, :author, spree_images_attributes: [:viewable_id, :attachment, :alt, :viewable_type, :id, :_destroy])
  end

  def material_params
    params.require(:material).permit(:title, :text, spree_images_attributes: [:viewable_id, :attachment, :alt, :viewable_type, :id, :_destroy])
  end

  def baloon_params
    params.require(:baloon).permit(:coords, :caption, :header, :body, :footer, :logo)
  end




end

app/controllers/spree/contact_us/contacts_controller.rb
class Spree::ContactUs::ContactsController < Spree::StoreController

  helper "spree/products"
  def create
    @contact = Spree::ContactUs::Contact.new(params[:contact_us_contact])

    if @contact.save
      if Spree::ContactUs::Config.contact_tracking_message.present?
        flash[:contact_tracking] = Spree::ContactUs::Config.contact_tracking_message
      end
      redirect_to(spree.root_path, :notice => Spree.t('contact_us.notices.success'))
    else
      redirect_to '/partnership'
    end
  end

  def new
    @contact = Spree::ContactUs::Contact.new
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  private

  def accurate_title
    Spree.t(:contact_us_title)
  end

end

app/controllers/spree/orders_controller.rb
module Spree
  class OrdersController < Spree::StoreController
    ssl_required :show

    before_filter :check_authorization
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/products', 'spree/orders'
    include ApplicationHelper

    respond_to :html

    before_filter :assign_order_with_lock, only: :update
    before_filter :apply_coupon_code, only: :update
    skip_before_filter :verify_authenticity_token

    def show
      @order = Order.find_by_number!(params[:id])
    end

    def update
      if @order.contents.update_cart(order_params)
        respond_with(@order) do |format|
          format.html do
            if params.has_key?(:checkout)
              @order.next if @order.cart?
              redirect_to checkout_state_path(@order.checkout_steps.first)
            else
              redirect_to cart_path
            end
          end
        end
      else
        respond_with(@order)
      end
    end

    # Shows the current incomplete order from the session
    def edit
      @order = current_order || Order.new
      associate_user
    end

    # Adds a new item to the order (creating a new order if none already exists)
    def populate
      v = Spree::Variant.find(params[:variant_id])
      if true_var(v.product)
      populator = Spree::OrderPopulator.new(current_order(create_order_if_necessary: true), current_currency)

      if populator.populate(params[:variant_id], params[:quantity])
        respond_with(@order) do |format|
          format.html { redirect_to :back }
        end
      else
        flash[:error] = populator.errors.full_messages.join(" ")
        redirect_back_or_default(spree.root_path)
      end
      else
        redirect_back_or_default(spree.root_path)
      end
    end

    def empty
      if @order = current_order
        @order.empty!
      end

      redirect_to spree.cart_path
    end

    def accurate_title
      if @order && @order.completed?
        Spree.t(:order_number, :number => @order.number)
      else
        Spree.t(:shopping_cart)
      end
    end

    def check_authorization
      cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
      order = Spree::Order.find_by_number(params[:id]) || current_order

      if order
        authorize! :edit, order, cookies.signed[:guest_token]
      else
        authorize! :create, Spree::Order
      end
    end

    private

      def order_params
        if params[:order]
          params[:order].permit(*permitted_order_attributes)
        else
          {}
        end
      end

      def assign_order_with_lock
        @order = current_order(lock: true)
        unless @order
          flash[:error] = Spree.t(:order_not_found)
          redirect_to root_path and return
        end
      end
  end
end

app/controllers/spree/static_content_controller.rb
class Spree::StaticContentController < Spree::StoreController
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  helper 'spree/products'
  layout :determine_layout

  def show
    @page = Spree::Page.visible.find_by_slug!(request.path)
  end

  def article
    @article = Article.friendly.find(params[:id])
  end

  private
    def determine_layout
      return @page.layout if @page and @page.layout.present? and not @page.render_layout_as_partial?
      Spree::Config.layout
    end

    def accurate_title
      @page ? (@page.meta_title.present? ? @page.meta_title : @page.title) : nil
    end
end

app/helpers/spree/base_helper.rb
module Spree
  module BaseHelper

    # Defined because Rails' current_page? helper is not working when Spree is mounted at root.
    def current_spree_page?(url)
      path = request.fullpath.gsub(/^\/\//, '/')
      if url.is_a?(String)
        return path == url
      elsif url.is_a?(Hash)
        return path == spree.url_for(url)
      end
      return false
    end

    def link_to_cart(text = nil)
      text = text ? h(text) : Spree.t('cart')
      css_class = nil

      if simple_current_order.nil? or simple_current_order.item_count.zero?
        text = "#{text}: (#{Spree.t('empty')})"
        css_class = 'empty'
      else
        text = "#{text}: (#{simple_current_order.item_count})  <span class='amount'>#{simple_current_order.display_total.to_html}</span>"
        css_class = 'full'
      end

      link_to text.html_safe, spree.cart_path, :class => "cart-info #{css_class}"
    end

    # human readable list of variant options
    def variant_options(v, options={})
      v.options_text
    end

    def meta_data
      object = instance_variable_get('@'+controller_name.singularize)
      meta = {}

      if object.kind_of? ActiveRecord::Base
        meta[:keywords] = object.meta_keywords if object[:meta_keywords].present?
        meta[:description] = object.meta_description if object[:meta_description].present?
      end

      if meta[:description].blank? && object.kind_of?(Spree::Product)
        meta[:description] = strip_tags(truncate(object.description, length: 160, separator: ' '))
      end

      meta.reverse_merge!({
        keywords: current_store.meta_keywords,
        description: current_store.meta_description,
      })
      meta
    end

    def meta_data_tags
      meta_data.map do |name, content|
        tag('meta', name: name, content: content)
      end.join("\n")
    end

    def body_class
      @body_class ||= content_for?(:sidebar) ? 'two-col' : 'one-col'
      @body_class
    end

    def logo(image_path=Spree::Config[:logo])
      link_to image_tag(image_path), spree.root_path
    end

    def flash_messages(opts = {})
      ignore_types = ["order_completed"].concat(Array(opts[:ignore_types]).map(&:to_s) || [])

      flash.each do |msg_type, text|
        unless ignore_types.include?(msg_type)
          concat(content_tag :div, text, class: "flash #{msg_type}")
        end
      end
      nil
    end

    def breadcrumbs(taxon, separator="&nbsp;&raquo;&nbsp;")
      return "" if current_page?("/") || taxon.nil?
      separator = raw(separator)
      crumbs = [content_tag(:li, link_to(raw('<i class="fa fa-home"></i>'), spree.root_path) + separator)]
      if taxon
        crumbs << content_tag(:li, link_to(Spree.t(:products), products_path) + separator)
        crumbs << taxon.ancestors.collect { |ancestor| content_tag(:li, link_to(ancestor.name , seo_url(ancestor)) + separator) } unless taxon.ancestors.empty?
        crumbs << content_tag(:li, content_tag(:span, link_to(taxon.name , seo_url(taxon))))
      else
        crumbs << content_tag(:li, content_tag(:span, Spree.t(:products)))
      end
      crumb_list = content_tag(:ul, raw(crumbs.flatten.map{|li| li.mb_chars}.join), class: 'inline')
      content_tag(:nav, crumb_list, id: 'breadcrumbs', class: 'sixteen columns')
    end

    def taxons_tree(root_taxon, current_taxon, max_level = 1)
      return '' if max_level < 1 || root_taxon.children.empty?
      content_tag :ul do
        root_taxon.children.map do |taxon|
          css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
          content_tag :li, class: css_class do
           link_to(taxon.name, seo_url(taxon)) +
           taxons_tree(taxon, current_taxon, max_level - 1)
          end
        end.join("\n").html_safe
      end
    end
    def taxons_tree2(root_taxon, current_taxon, max_level = 1)
      content_tag :ul do
        root_taxon.children.map do |taxon|
          css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
          content_tag :li, class: css_class do
           link_to(taxon.name, seo_url(taxon)) +
           taxons_tree_br(taxon, current_taxon)
          end
        end.join("\n").html_safe
      end
    end
    def taxons_tree_br(brand, current_taxon)
      content_tag :ul do

        Spree::Taxon.find_by_name('Категории').children.map do |taxon|
          css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
          content_tag :li, class: css_class do
            link_to(taxon.name, seo_url(taxon))
                # taxons_tree(taxon, current_taxon, max_level - 1)
          end
        end.join("\n").html_safe
      end
    end

    def available_countries
      checkout_zone = Zone.find_by(name: Spree::Config[:checkout_zone])

      if checkout_zone && checkout_zone.kind == 'country'
        countries = checkout_zone.country_list
      else
        countries = Country.all
      end

      countries.collect do |country|
        country.name = Spree.t(country.iso, scope: 'country_names', default: country.name)
        country
      end.sort_by { |c| c.name.parameterize }
    end

    def seo_url(taxon)
      return spree.nested_taxons_path(taxon.permalink)
    end

    def gem_available?(name)
       Gem::Specification.find_by_name(name)
    rescue Gem::LoadError
       false
    rescue
       Gem.available?(name)
    end

    def display_price(product_or_variant)
      product_or_variant.price_in(current_currency).display_price.to_html if spree_current_user

    end

    def pretty_time(time)
      [I18n.l(time.to_date, format: :long),
        time.strftime("%l:%M %p")].join(" ")
    end

    def method_missing(method_name, *args, &block)
      if image_style = image_style_from_method_name(method_name)
        define_image_method(image_style)
        self.send(method_name, *args)
      else
        super
      end
    end

    def link_to_tracking(shipment, options = {})
      return unless shipment.tracking

      if shipment.tracking_url
        link_to(shipment.tracking, shipment.tracking_url, options)
      else
        content_tag(:span, shipment.tracking)
      end
    end

    private
    # Returns style of image or nil
    def image_style_from_method_name(method_name)
      if style = method_name.to_s.sub(/_image$/, '')
        possible_styles = Spree::Image.attachment_definitions[:attachment][:styles]
        style if style.in? possible_styles.with_indifferent_access
      end
    end

    def create_product_image_tag(image, product, options, style)
      options.reverse_merge! alt: image.alt.blank? ? product.name : image.alt
      image_tag image.attachment.url(style), options
    end

    def define_image_method(style)
      self.class.send :define_method, "#{style}_image" do |product, *options|
        options = options.first || {}
        if product.images.empty?
          if !product.is_a?(Spree::Variant) && !product.variant_images.empty?
            create_product_image_tag(product.variant_images.first, product, options, style)
          else
            if product.is_a?(Variant) && !product.product.variant_images.empty?
              create_product_image_tag(product.product.variant_images.first, product, options, style)
            else
              image_tag "noimage/#{style}.png", options
            end
          end
        else
          create_product_image_tag(product.images.first, product, options, style)
        end
      end
    end
  end
end

app/views/spree/products/_cart_form.html.erb
<%= form_for :order, :url => populate_orders_path do |f| %>
  <div id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="http://schema.org/Offer">

    <% if @product.variants_and_option_values(current_currency).any? %>
      <div id="product-variants" class="columns five alpha">
        <h6 class="product-section-title"><%= Spree.t(:variants) %></h6>
        <ul>
          <% @product.variants_and_option_values(current_currency).each_with_index do |variant, index| %>
            <li>
              <%= radio_button_tag "variant_id", variant.id, index == 0, 'data-price' => variant.price_in(current_currency).money  %>
              <%= label_tag "variant_id_#{ variant.id }" do %>
                <span class="variant-description">
                  <%= variant_options variant %>
                </span>
                <% if variant_price variant %>
                  <span class="price diff"><%= variant_price variant %></span>
                <% end %>

                <% unless variant.can_supply? %>
                  <span class="out-of-stock"><%= Spree.t(:out_of_stock) %></span>
                <% end %>
              <% end %>
            </li>
          <% end%>
        </ul>
      </div>
    <% else %>
      <%= hidden_field_tag "variant_id", @product.master.id %>
    <% end %>

    <% if @product.price_in(current_currency) and !@product.price.nil? %>
      <div data-hook="product_price" class="columns five <% if !@product.has_variants? %> alpha <% else %> omega <% end %>">

        <div id="product-price">
          <h6 class="product-section-title"><%= Spree.t(:price) %></h6>
          <div>
            <span class="price selling" itemprop="price">
              <%= display_price(@product) %>
            </span>
            <span itemprop="priceCurrency" content="<%= @product.currency %>"></span>
          </div>

          <% if @product.master.can_supply? %>
            <link itemprop="availability" href="http://schema.org/InStock" />
          <% elsif @product.variants.empty? %>
            <br />
            <span class="out-of-stock"><%= Spree.t(:out_of_stock) %></span>
          <% end %>
        </div>

        <div class="add-to-cart">
          <%= number_field_tag :quantity, 1, :class => 'title', :min => 1 %>
          <%= button_tag :class => 'large primary', :id => 'add-to-cart-button', :type => :submit do %>
            <%= Spree.t(:add_to_cart) %>
          <% end %>
        </div>
      </div>
    <% else %>
        <div id="product-price">
          <br>
          <div><span class="price selling" itemprop="price"><%= Spree.t('product_not_available_in_this_currency') %></span></div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/spree/products/_image.html.erb
<% if defined?(image) && image %>
  <%= image_tag image.attachment.url(:product), :itemprop => "image" %>
<% else %>
  <%= product_image(@product, :itemprop => "image") %>
<% end %>

app/views/spree/products/_promotions.html.erb
<% promotions = @product.possible_promotions %>
<% if promotions.any? %>
  <div id="promotions">
    <h3><%= Spree.t(:promotions) %></h3>
    <% promotions.each do |promotion| %>
    <div>
      <h4><%= promotion.name %></h4>
      <p><%= promotion.description %></p>
      <% if promotion.products.any? %>
      <ul>
        <% promotion.products.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/spree/products/_properties.html.erb
<% unless @product_properties.empty? %>  
  <h6 class="product-section-title"><%= Spree.t('properties')%></h6>
  <table id="product-properties" class="table-display" data-hook>
    <tbody>
      <% @product_properties.each do |product_property| %>
        <% css_class = cycle('even', 'odd', :name => "properties") %>
        <tr class="<%= css_class %>">
          <td><strong><%= product_property.property.name %></strong></td>
          <td><%= product_property.value %> <%= product_property.property.presentation %></td>
        </tr>
      <% end %>
      <% reset_cycle('properties') %>
    </tbody>
  </table>
<% end %>

app/views/spree/products/_taxons.html.erb
<% if !@product.taxons.blank? %>
  <div id="taxon-crumbs" data-hook class="alpha columns five omega">
    <h6 class="product-section-title"><%= Spree.t(:look_for_similar_items) %></h6>

    <div data-hook="product_taxons">
      <ul id="similar_items_by_taxon" data-hook>
      <% @product.taxons.each do |taxon| %>
        <li><%= link_to taxon.name, seo_url(taxon) %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

app/views/spree/products/_thumbnails.html.erb
<%# no need for thumbnails unless there is more than one image %>
<% if (@product.images + @product.variant_images).uniq.size > 1 %>
  <ul id="product-thumbnails" class="thumbnails inline" data-hook>
    <% @product.images.each do |i| %>
      <li class='tmb-all tmb-<%= i.viewable.id %>'>
        <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
      </li>
    <% end %>

    <% if @product.has_variants? %>
      <% @product.variant_images.each do |i| %>
        <% next if @product.images.include?(i) %>
        <li class='vtmb tmb-<%= i.viewable.id %>'>
          <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/spree/products/index.html.slim
- content_for :bodyClass, 'products'
- if params[:keywords]
  h1 = params[:keywords]
  .row
    -@products.each do |product|
      = render partial: 'spree/custom_shared/product', locals: {product: product}

app/views/spree/products/show.html.slim
- content_for :bodyClass, "product #{(params[:taxon_id].present?)? ((@taxon.depth < 2)? "category_#{@taxon.id}" : "category_#{@taxon.parent.id}" ) : ((@product.taxons.first.depth < 2)? "category_#{@product.taxons.first.id}" : "category_#{@product.taxons.first.parent.id}" )}"
.left
  .fotorama data-nav="thumbs" data-width="100%"
    - @product.images.each do |i|
      = image_tag(i.attachment.url(:large))
  .similarProducts
    h2 Похожие товары
    .row
      - @product.taxons.first.products.limit(6).each do |p|
        - p.variants.each do |variant|
          - if spree_current_user
            - if variant.option_values.first.name.to_i == spree_current_user.price_kind.to_i or spree_current_user.price_kind.to_i == -1
              - @true_var = variant
        section class="product supershit new awesome cool"
          .imgWrap
            = link_to product_image(p, :itemprop => "image"), product_url(p, :taxon_id => @taxon.try(:id))
          h2
            = link_to p.name, product_url(p, :taxon_id => @taxon.try(:id))
          - if @true_var
            = form_for :order, :url => populate_orders_path, html: {class: 'price'} do |f|
              = hidden_field_tag "variant_id", @true_var.id
              .price = display_price(@true_var)
              - @true_var = nil

              = hidden_field_tag :quantity, 1
              button.toCart type="submit"
                i class="fa fa-shopping-cart"
                | в корзину




.right
  h1 = @product.name
  - brand = @product.taxons.where(parent_id: 12).first
  - if brand
    a.brand href="#"
      - if !@product.taxons.where(parent_id: 12).empty? and brand.icon.url(:normal) != '/assets/default_taxon.png'
        = link_to(image_tag(brand.icon.url(:normal)), seo_url(brand))
      - else
        = link_to brand.name, seo_url(brand)
  p = raw strip_tags @product.description
  / В этом блоке тоже можешь вставить как там по дефолту, я скорее всего поправлю
  /form.price
  /  .amount = display_price(@product)
  = render 'spree/custom_shared/cart_form_custom'
  .files
    a.manual href="#{@product.instruction}" target="_blank"
      =' icon 'wrench'
      | инструкция
    a.certificate href="#{@product.certificate}" target="_blank"
      =' icon 'file-text'
      | сертификат
  / Выведи как она есть, я сам кастомизирую
  table.specs
    - @product_properties.each do |product_property|
      tr
        td.type = product_property.property.name
        td.value = product_property.value + ' ' + product_property.property.presentation

app/views/spree/products/show_old.html.erb
<% cache [I18n.locale, current_currency, @product] do %>
  <div data-hook="product_show" itemscope itemtype="http://schema.org/Product">
    <% @body_id = 'product-details' %>

    <div class="columns six alpha" data-hook="product_left_part">
      <div class="row" data-hook="product_left_part_wrap">

        <div id="product-images" data-hook="product_images">
          <div id="main-image" data-hook>
            <%= render :partial => 'image' %>
          </div>
          <div id="thumbnails" data-hook>
            <%= render :partial => 'thumbnails' %>
          </div>
        </div>

        <div data-hook="product_properties">
          <%= render :partial => 'properties' %>
        </div>

        <div data-hook="promotions">
          <%= render :partial => 'promotions' %>
        </div>

      </div>
    </div>

    <div class="columns ten omega" data-hook="product_right_part">
      <div class="row" data-hook="product_right_part_wrap">

        <div id="product-description" data-hook="product_description">

          <h1 class="product-title" itemprop="name"><%= accurate_title %></h1>

          <div itemprop="description" data-hook="description">
            <%= product_description(@product) rescue Spree.t(:product_has_no_description) %>
          </div>

          <div id="cart-form" data-hook="cart_form">
            <%= render :partial => 'cart_form' %>
          </div>

        </div>

        <%= render :partial => 'taxons' %>

      </div>
    </div>

  </div>
<% end %>