config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  get '/articles/:id' => 'spree/static_content#article'
  get '/admin/articles' => 'spree/admin/pages#articles_index'
  get '/admin/add_article' => 'spree/admin/pages#add_article'
  get '/admin/edit_article/:article_item_id' => 'spree/admin/pages#edit_article'
  get '/admin/delete_article/:article_item_id' => 'spree/admin/pages#delete_article'
  post '/articles' => 'articles#create_article'
  patch '/articles' => 'spree/admin/pages#update_article'

  get '/admin/baloons' => 'spree/admin/pages#baloons_index'
  get '/admin/add_baloon' => 'spree/admin/pages#add_baloon'
  get '/admin/edit_baloon/:baloon_item_id' => 'spree/admin/pages#edit_baloon'
  get '/admin/delete_baloon/:baloon_item_id' => 'spree/admin/pages#delete_baloon'
  post '/baloons' => 'spree/admin/pages#create_baloon'
  patch '/baloons' => 'spree/admin/pages#update_baloon'

  get '/admin/materials' => 'spree/admin/pages#materials_index'
  get '/admin/add_material' => 'spree/admin/pages#add_material'
  get '/admin/edit_material/:material_item_id' => 'spree/admin/pages#edit_material'
  get '/admin/delete_material/:material_item_id' => 'spree/admin/pages#delete_material'
  post '/materials' => 'spree/admin/pages#create_material'
  patch '/materials' => 'spree/admin/pages#update_material'

  get 'export_xml' => 'spree/products#xml_export', :defaults => { :format => 'xml' }

end

app/controllers/spree/admin/products_controller.rb
module Spree
  module Admin
    class ProductsController < ResourceController
      helper 'spree/products'

      before_filter :load_data, :except => :index
      create.before :create_before
      update.before :update_before
      helper_method :clone_object_url

      def show
        session[:return_to] ||= request.referer
        redirect_to( :action => :edit )
      end

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def update
        if params[:product][:taxon_ids].present?
          params[:product][:taxon_ids] = params[:product][:taxon_ids].split(',')
        end
        if params[:product][:option_type_ids].present?
          params[:product][:option_type_ids] = params[:product][:option_type_ids].split(',')
        end
        invoke_callbacks(:update, :before)





        # name = params[:product][:certificate].original_filename
        # directory = "public/files"
        # path = File.join(directory, name)
        # File.open(path, "wb") { |f| f.write(params[:product][:certificate].read) }
        #
        instruction = params[:product][:instruction]
        cert = params[:product][:certificate]
        artikul = params[:product][:artikul]
        params[:product][:certificate] = nil
        params[:product][:instruction] = nil

        if @object.update_attributes(permitted_resource_params)
          unless cert.blank?
            name = cert.original_filename
            directory = "public/certificates"
            path = File.join(directory, name)
            File.open(path, "wb") { |f| f.write(cert.read) }
            @object.certificate = '/certificates/'+path.split('/').last
            @object.save!
          end
          unless instruction.blank?
            name = instruction.original_filename
            directory = "public/instructions"
            path = File.join(directory, name)
            File.open(path, "wb") { |f| f.write(instruction.read) }
            @object.instruction = '/instructions/'+path.split('/').last
            @object.save!
          end
          @object.artikul = artikul
          invoke_callbacks(:update, :after)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
            format.js   { render :layout => false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to update the product again
          @product.slug = @product.slug_was if @product.slug.blank?
          invoke_callbacks(:update, :fails)
          respond_with(@object)
        end
      end

      def destroy
        @product = Product.friendly.find(params[:id])
        @product.destroy

        flash[:success] = Spree.t('notice_messages.product_deleted')

        respond_with(@product) do |format|
          format.html { redirect_to collection_url }
          format.js  { render_js_for_destroy }
        end
      end

      def clone
        @new = @product.duplicate

        if @new.save
          flash[:success] = Spree.t('notice_messages.product_cloned')
        else
          flash[:error] = Spree.t('notice_messages.product_not_cloned')
        end

        redirect_to edit_admin_product_url(@new)
      end

      def stock
        @variants = @product.variants
        @variants = [@product.master] if @variants.empty?
        @stock_locations = StockLocation.accessible_by(current_ability, :read)
        if @stock_locations.empty?
          flash[:error] = Spree.t(:stock_management_requires_a_stock_location)
          redirect_to admin_stock_locations_path
        end
      end

      protected

        def find_resource
          Product.with_deleted.friendly.find(params[:id])
        end

        def location_after_save
          spree.edit_admin_product_url(@product)
        end

        def load_data
          @taxons = Taxon.order(:name)
          @option_types = OptionType.order(:name)
          @tax_categories = TaxCategory.order(:name)
          @shipping_categories = ShippingCategory.order(:name)
        end

        def collection
          return @collection if @collection.present?
          params[:q] ||= {}
          params[:q][:deleted_at_null] ||= "1"

          params[:q][:s] ||= "name asc"
          @collection = super
          @collection = @collection.with_deleted if params[:q][:deleted_at_null] == '0'
          # @search needs to be defined as this is passed to search_form_for
          @search = @collection.ransack(params[:q])
          @collection = @search.result.
                distinct_by_product_ids(params[:q][:s]).
                includes(product_includes).
                page(params[:page]).
                per(Spree::Config[:admin_products_per_page])

          @collection
        end

        def create_before
          return if params[:product][:prototype_id].blank?
          @prototype = Spree::Prototype.find(params[:product][:prototype_id])
        end

        def update_before
          # note: we only reset the product properties if we're receiving a post from the form on that tab
          return unless params[:clear_product_properties]
          params[:product] ||= {}
        end

        def product_includes
          [{ :variants => [:images], :master => [:images, :default_price]}]
        end

        def clone_object_url resource
          clone_admin_product_url resource
        end

        def permit_attributes
          params.require(:product).permit!
        end
    end
  end
end

app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < Spree::StoreController
    before_filter :load_product, :only => :show
    before_filter :load_taxon, :only => :index

    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      @searcher = build_searcher(params)
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    def xml_export
     url = request.protocol+request.host_with_port
     xm = []
     Spree::Product.limit(20).each do |p|
       h={}
       h['артикул'] = p.sku
       h['название'] = p.name
       h['фото'] = url+p.variant_images.first.attachment.url unless p.variant_images.empty?
       h['ссылка на товар'] = product_url(p)
       h['описание'] = p.description
       sv = {}
       p.product_properties.includes(:property).each do |prop|
         # unless (prop.value.blank? or prop.property.presentation.blank? or prop.property.name.blank?)
         sv["#{prop.property.name}"] = prop.value.to_s + ' ' + prop.property.presentation.to_s
         # end
       end
       h['свойства'] = sv
       xm << h
      end
     render :xml => xm.to_xml
    end

    def show
      @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
      @product_properties = @product.product_properties.includes(:property)
      @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
    end

    private
      def accurate_title
        @product ? @product.name : super
      end

      def load_product
        if try_spree_current_user.try(:has_spree_role?, "admin")
          @products = Product.with_deleted
        else
          @products = Product.active(current_currency)
        end
        @product = @products.friendly.find(params[:id])
      end

      def load_taxon
        @taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon].present?
      end
  end
end

app/views/spree/admin/products/_add_stock_form.html.erb
<%= form_for [:admin, Spree::StockMovement.new], url: admin_stock_items_path do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:add_stock_management) %></legend>

    <div data-hook="admin_stock_movements_form_fields" class="row">
      <div class="alpha two columns">
        <%= f.field_container :quantity do %>
          <%= f.label :quantity, Spree.t(:quantity) %>
          <%= f.number_field :quantity, class: 'fullwidth', value: 1 %>
        <% end %>
      </div>
      <div class="five columns">
        <%= f.field_container :stock_location do %>
          <%= label_tag :stock_location_id, Spree.t(:stock_location) %>
          <%= select_tag 'stock_location_id', options_from_collection_for_select(@stock_locations, :id, :name),
            class: 'select2 fullwidth' %>
        <% end %>
      </div>

      <div class="five columns omega">
        <%= f.field_container :variant_id do %>
          <%= label_tag 'variant_id', Spree.t(:variant) %>
          <%= select_tag 'variant_id', options_from_collection_for_select(@variants, :id, :sku_and_options_text),
            class: 'select2 fullwidth' %>
        <% end %>
      </div>
    </div>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:add_stock), 'plus' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), collection_url, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/products/_autocomplete.js.erb
<script type='text/template' id='product_template'>
  <li id="product_{{ product.id }}" data-product-id="{{product.id }}" class="columns three alpha small_product">
    <div class="product-image">
      {{#if product.image }}
        <img src='{{product.image}}' alt='{{ product.name }}' />
      {{ else }}
        <img src='<%= image_path("noimage/small.png") %>' alt='{{product.name }}' />
      {{/if}}
    </div>
    <a class="name">{{ product.name }}</a><br>
    <span class="price">{{ product.display_price }}</span>
  </li>
</script>

app/views/spree/admin/products/_form.html.erb
<div data-hook="admin_product_form_fields">

  <div class="left eight columns alpha" data-hook="admin_product_form_left">
    <div data-hook="admin_product_form_name">
      <%= f.field_container :name do %>
        <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', :class => 'required')) %>
        <%= f.text_field :name, :class => 'fullwidth title' %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_slug">
      <%= f.field_container :slug do %>
        <%= f.label :slug, raw(Spree.t(:slug) + content_tag(:span, ' *',  :class => "required")) %>
        <%= f.text_field :slug, :class => 'fullwidth title' %>
        <%= f.error_message_on :slug %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_description">
      <%= f.field_container :description do %>
        <%= f.label :description, Spree.t(:description) %>
        <%= f.text_area :description, {:rows => "#{unless @product.has_variants? then '20' else '13' end}", :class => 'fullwidth'} %>
        <%= f.error_message_on :description %>
      <% end %>
    </div>
  </div>

  <div class="right four columns omega" data-hook="admin_product_form_right">
    <div data-hook="admin_product_form_price">
    <%= f.field_container :price do %>
      <%= f.label :price, raw(Spree.t(:master_price) + content_tag(:span, ' *', :class => "required")) %>
      <%= f.text_field :price, :value => number_to_currency(@product.price, :unit => '') %>
      <%= f.error_message_on :price %>
    <% end %>
    </div>

    <div data-hook="admin_product_form_cost_price" class="alpha two columns">
      <%= f.field_container :cost_price do %>
        <%= f.label :cost_price, Spree.t(:cost_price) %>
        <%= f.text_field :cost_price, :value => number_to_currency(@product.cost_price, :unit => '') %>
        <%= f.error_message_on :cost_price %>
      <% end %>
    </div>
    <div data-hook="admin_product_form_cost_currency" class="omega two columns">
      <%= f.field_container :cost_currency do %>
        <%= f.label :cost_currency, Spree.t(:cost_currency) %>
        <%= f.text_field :cost_currency %>
        <%= f.error_message_on :cost_currency %>
      <% end %>
    </div>

    <div class="clear"></div>

    <div data-hook="admin_product_form_available_on">
      <%= f.field_container :available_on do %>
        <%= f.label :available_on, Spree.t(:available_on) %>
        <%= f.error_message_on :available_on %>
        <%= f.text_field :available_on, :value => datepicker_field_value(@product.available_on), :class => 'datepicker' %>
      <% end %>
    </div>


    <div data-hook="admin_product_form_shipping_categories">
      <%= f.hidden_field :shipping_category_id, value: Spree::ShippingCategory.all.first.id %>
    </div>

    <div data-hook="admin_product_form_shipping_categories">
      <%= f.label :certificate, 'Сертификат' %>
      <%= f.file_field :certificate %>
      <%= link_to f.object.certificate.split('/').last, f.object.certificate, target: '_blank' if f.object.certificate %>
    </div>
    <div data-hook="admin_product_form_shipping_categories">

      <%= f.label :instruction, 'Инструкция' %>

      <%= f.file_field :instruction %>
      <%= link_to f.object.instruction.split('/').last, f.object.instruction, target: '_blank' if f.object.instruction %>
    </div>




  </div>

  <div class="twelve columns alpha omega">
    <div data-hook="admin_product_form_taxons">
      <%= f.field_container :taxons do %>
        <%= f.label :taxon_ids, Spree.t(:taxons) %><br />
        <%= f.hidden_field :taxon_ids, :value => @product.taxon_ids.join(',') %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_option_types">
      <%= f.field_container :option_types do %>
        <%= f.label :option_type_ids, Spree.t(:option_types) %>
        <%= f.hidden_field :option_type_ids, :value => @product.option_type_ids.join(',') %>
      <% end %>
    </div>
  </div>

  <div data-hook="admin_product_form_meta" class="alpha omega twelve columns">
    <div data-hook="admin_product_form_meta_keywords">
      <%= f.field_container :meta_keywords do %>
        <%= f.label :meta_keywords, Spree.t(:meta_keywords) %>
        <%= f.text_field :meta_keywords, :class => 'fullwidth' %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_meta_description">
      <%= f.field_container :meta_description do %>
        <%= f.label :meta_description, Spree.t(:meta_description) %>
        <%= f.text_field :meta_description, :class => 'fullwidth' %>
      <% end %>
    </div>
  </div>

  <div class="clear"></div>

  <div data-hook="admin_product_form_additional_fields"></div>

  <div class="clear"></div>
</div>

<% unless Rails.env.test? %>
  <script>
  $('.select2-container').css({width: '20em'})
  </script>
<% end %>

app/views/spree/admin/products/_properties_form.erb
<% content_for :page_title do %>
  <%= Spree.t(:properties) %>
<% end %>

<% f.fields_for :product_properties do |properties_form| %>
    <div data-hook="value">
      <%= properties_form.label :value, properties_form.object.property.presentation %><br />
      <%= properties_form.text_field :value %>
    </div>
<% end %>

app/views/spree/admin/products/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_products_list), session[:return_to] || admin_products_url, :icon => 'arrow-left' %></li>
  <% if can?(:create, Spree::Product) %>
    <li id="new_product_link">
      <%= button_link_to Spree.t(:new_product), new_object_url, { :icon => 'plus', :id => 'admin_new_product' } %>
    </li>
  <% end %>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Product Details' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/products/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_products) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_product_link">
    <%= button_link_to Spree.t(:new_product), new_object_url, { :remote => true, :icon => 'plus', :id => 'admin_new_product' } %>
  </li>
<% end if can?(:create, Spree::Product) %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>

        <%- locals = {:f => f} %>

        <div data-hook="admin_products_index_search">
          <div class="alpha nine columns">
            <div class="field">
              <%= f.label :name_cont, Spree.t(:name) %>
              <%= f.text_field :name_cont, :size => 15 %>
            </div>
          </div>
          <div class="four columns">
            <div class="field">
              <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
              <%= f.text_field :variants_including_master_sku_cont, :size => 15 %>
            </div>
          </div>
          <div class="three columns omega">
            <div class="field checkbox">
              <label>
                <%= f.check_box :deleted_at_null, {:checked => params[:q][:deleted_at_null] == '0'}, '0', '1' %>
                <%= Spree.t(:show_deleted) %>
              </label>
            </div>
          </div>
        </div>

        <div class="clear"></div>

        <div class="form-buttons actions filter-actions" data-hook="admin_products_index_search_buttons">
          <%= button Spree.t(:search), 'search' %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_product_wrapper" data-hook></div>

<%= paginate @collection %>

<% if @collection.any? %>
  <table class="index" id="listing_products">
    <colgroup>
       <col style="width: 15%;">
       <col style="width: 10%;">
       <col style="width: 48%;">
       <col style="width: 10%;">
       <col style="width: 17%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:sku) %></th>
        <th colspan="2"><%= sort_link @search,:name, Spree.t(:name), { :default_order => "desc" }, {:title => 'admin_products_listing_name_title'} %></th>
        <th><%= sort_link @search,:master_default_price_amount, Spree.t(:master_price), {}, {:title => 'admin_products_listing_price_title'} %></th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="align-center"><%= product.sku rescue '' %></td>
            <td class="align-center"><%= mini_image(product) %></td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="align-center"><%= product.display_price.to_html rescue '' %></td>
            <td class="actions" data-hook="admin_products_index_row_actions">
              <%= link_to_edit product, :no_text => true, :class => 'edit' if can?(:edit, product) && !product.deleted? %>
              &nbsp;
              <%= link_to_clone product, :no_text => true, :class => 'clone' if can?(:clone, product) %>
              &nbsp;
              <%= link_to_delete product, :no_text => true if can?(:delete, product) && !product.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/product')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_product_path %>!
  </div>
<% end %>

<%= paginate @collection %>

app/views/spree/admin/products/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_product">

    <legend align="center"><%= Spree.t(:new_product) %></legend>

    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
      <%= f.text_field :name, :class => 'fullwidth title' %>
      <%= f.error_message_on :name %>
    <% end %>

    <div data-hook="new_product_attrs" class="row">
      <% unless @product.has_variants? %>
        <div data-hook="new_product_sku" class="alpha four columns">
          <%= f.field_container :sku do %>
            <%= f.label :sku, Spree.t(:sku) %><br />
            <%= f.text_field :sku, :size => 16, :class => 'fullwidth' %>
            <%= f.error_message_on :sku %>
          <% end %>
        </div>
      <% end %>

      <div data-hook="new_product_prototype" class="four columns">
        <%= f.field_container :prototype do %>
          <%= f.label :prototype_id, Spree.t(:prototype) %><br />
          <%= f.collection_select :prototype_id, Spree::Prototype.all, :id, :name, {:include_blank => true}, {:class => 'select2 fullwidth'} %>
        <% end %>
      </div>

      <div data-hook="new_product_price" class="four columns">
        <%= f.field_container :price do %>
          <%= f.label :price, Spree.t(:master_price) %> <span class="required">*</span><br />
          <%= f.text_field :price, :value => number_to_currency(@product.price, :unit => ''), :class => 'fullwidth' %>
          <%= f.error_message_on :price %>
        <% end %>
      </div>

      <div data-hook="new_product_available_on" class="omega four columns">
        <%= f.field_container :available_on do %>
          <%= f.label :available_on, Spree.t(:available_on) %>
          <%= f.error_message_on :available_on %>
          <%= f.text_field :available_on, :class => 'datepicker fullwidth' %>
        <% end %>
      </div>

    </div>

    <div class='row'>
      <div data-hook="new_product_shipping_category" class="alpha four columns">
        <%= f.field_container :shipping_category do %>
          <%= f.label :shipping_category_id, Spree.t(:shipping_categories) %><span class="required">*</span><br />
          <%= f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2 fullwidth' }) %>
          <%= f.error_message_on :shipping_category_id %>
        <% end %>
      </div>
    </div>

    <div class="clearfix" data-hook="product-from-prototype" id="product-from-prototype">
      <%= render :file => 'spree/admin/prototypes/show' if @prototype %>
    </div>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>

<script type="text/javascript">
//<![CDATA[
  (function($){
    var base_url = "<%= admin_prototypes_url %>";
    var prototype_select = $('#product_prototype_id');
    prototype_select.change(function() {
      var id = prototype_select.val();
      if (id.length) {
        var url = new Uri(base_url);
        url.setPath(url.path() + '/' + id);
        $('#product-from-prototype').load(url.toString());
      } else {
        $('#product-from-prototype').empty();
      }
    })
    if (prototype_select.html() == "") {
      prototype_select.change();
    }
  })(jQuery);
//]]>
</script>

app/views/spree/admin/products/new.js.erb
$("#new_product_wrapper").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
handle_date_picker_fields();
<% unless Rails.env.test? %>
  $('.select2').select2();
<% end %>
$("#table-filter").hide();
$("#admin_new_product").parent().hide();

app/views/spree/admin/products/stock.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_products_list), session[:return_to] || admin_products_url, :icon => 'arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Stock Management' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<div id="add_stock_form">
  <%= render 'add_stock_form' %>
</div>

<table class="index" id="listing_product_stock">
  <colgroup>
    <col style="width: 25%" />
    <col style="width: 25%" />
    <col style="width: 25%" />
    <col style="width: 25%" />
  </colgroup>
  <thead>
    <tr data-hook="admin_product_stock_management_index_headers">
      <th><%= Spree.t(:variant) %></th>
      <th colspan="4"><%= Spree.t(:stock_location_info) %></th>
    </tr>
  </thead>
  <tbody>
    <% @variants.each do |variant| %>
      <% if variant.stock_items.present? %>
        <tr id="<%= spree_dom_id variant %>" data-hook="admin_product_stock_management_index_rows" class="<%= cycle('odd', 'even') %>">
          <td class="align-center">
            <%= variant.sku_and_options_text %>
            <br>
            <% if variant.images.present? %>
              <%= image_tag variant.images.first.attachment.url(:mini) %>
            <% end %>
            <br/>
            <%= form_tag admin_product_variants_including_master_path(@product, variant, format: :js), method: :put, class: 'toggle_variant_track_inventory' do %>
                <%= check_box_tag 'track_inventory', 1, variant.track_inventory?,
                                  class: 'track_inventory_checkbox' %>
                <%= Spree.t(:track_inventory) %>
                <%= hidden_field_tag 'variant[track_inventory]', variant.track_inventory?,
                    class: 'variant_track_inventory',
                    id: "variant_track_inventory_#{variant.id}" %>
            <% end %>
          </td>
          <td colspan="4" class="stock_location_info">
            <table>
              <colgroup>
                <col style="width: 45%" />
                <col style="width: 20%" />
                <col style="width: 20%" />
                <col style="width: 15%" />
              </colgroup>
              <thead>
                <th><%= Spree.t(:stock_location) %></th>
                <th><%= Spree.t(:count_on_hand) %></th>
                <th><%= Spree.t(:backorderable) %></th>
                <th class="actions"></th>
              </thead>
              <tbody>
                <% variant.stock_items.each do |item| %>
                  <% next unless @stock_locations.include?(item.stock_location) %>

                  <tr id="stock-item-<%= item.id %>" class="<%= cycle('odd', 'even', :name => 'stock_locations')%>">
                    <td class="align-center"><%= item.stock_location.name %></td>
                    <td class="align-center"><%= item.count_on_hand %></td>
                    <td class="align-center">
                      <%= form_tag admin_stock_item_path(item), method: :put, class: 'toggle_stock_item_backorderable' do %>
                        <%= check_box_tag 'stock_item[backorderable]', true,
                              item.backorderable?,
                              class: 'stock_item_backorderable',
                              id: "stock_item_backorderable_#{item.stock_location.id}" %>
                      <% end %>
                    </td>
                    <td class="actions">
                      <%= link_to(icon('delete'), [:admin, item],
                            method: :delete, remote: true,
                            class: 'icon_link with-tip fa fa-trash no-text',
                            title: Spree.t(:remove), data: { action: :remove, confirm: Spree.t(:are_you_sure) }) %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </td>
          <% reset_cycle("stock_locations") %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>